### ISSUE TITLE
Download the dataset?

### ISSUE THREAD

**Issue by struggleeveryday** [Livox-SDK/livox-dataset-devkit#1]
Hi, I'm very intersted in livox dataset, but don't know where to download the dataset.
Is there a way to download livox dataset?
Thanks!

**Comment by russellyq** [comment]
@struggleeveryday @Livox-SDK  
hi I have bought one livox lidar as well. May I have this livox dataset ?
Thanks

**Comment by Livox-SDK** [comment]
Hi 
We really admire your interest in using Livox products. For the dataset please visit the link down below:
livoxtech.com/cn/dataset
@struggleeveryday, @russellyq
